### PR TITLE
Modification proposal. Do you think can be merged to your origin branch?

### PR DESCRIPTION
**Pull request by MaurizioMalaspina**
**Modifications on library:**

- Fixed CS5490::calibrate - |= vs &= on bitwise operations

- Added /RESET pin management (constructor overloading)
- Added not blocking register reading with check on operation result
- Added internal voltage reference checkInternalVoltageReference (according to "Errata: CS5490 Rev B2 Silicon (Mar'13) - Erratum 2 "On chip reference reset state")
- Added sendCalibrationCommand method (with no settle time delay)
- Added some not fundamental methods

- Enriched "keywords.txt"

**Modification on examples:**

- Added "CS5490_AC_Current_Gain_Tuning_demo.ino" example - a practical application built on CDB5490U evaluation board for sensing on AC line with current gain calibration

### CODE REVIEW

**Comment by tiagolobao** [comment]
First, I'll thank you a lot for the proposal.

> Fixed CS5490::calibrate - |= vs &= on bitwise operations

As you may have notice by fixing this. I could not test the calibration methods.
There are many methods and code that I can't do many tests. I'm reading everything to understand what you made, but I'll trust your tests

> Added /RESET pin management (constructor overloading)
> Enriched "keywords.txt"
> Added not blocking register reading with check on operation result

Nice changes.

> Added "CS5490_AC_Current_Gain_Tuning_demo.ino" example - a practical application built on CDB5490U evaluation board for sensing on AC line with current gain calibration

I still don't like this kind of operation like the code below, but I have no other ideas. Arduino unfortunately don't support try..catch operations :/

```cpp
  double rmsV = line.getRmsV();
  if (!line.isLastReadingOperationSucceeded()) registerReadingOperationIsOK = false;
  double freq = line.getFreq();
```

I'll merge everything and make some other changes before next release. I just need some time.
Thanks again

**Comment by MaurizioMalaspina** [comment]
It's a pleasure to contribute your project!

I can assure all is properly working here on my testbench. In every case I'll send you new pull request in case some bug to fix will arise (together with the related fixes, naturally!).

>I still don't like this kind of operation like the code below, but I have no other ideas. Arduino unfortunately don't support try..catch operations :/

```
 double rmsV = line.getRmsV();
  if (!line.isLastReadingOperationSucceeded()) registerReadingOperationIsOK = false;
  double freq = line.getFreq();
```

Yes, that was just a "poor programmer"'s solution in order not to modify your base code ;-)
A cleaner way to write the code could be something as what follow, by defining methods that get a reference to the output parameter (Arduino staff advices not to use pointers, because error prones) and return the result of the operation (i.e. a bool, despite I know Arduino staff deprecates the use of boolean variables):


`bool getRmsV(double &retVal); // method declaration in header file`

and use it as follow:

```
double rmsV;

if(line.getRmsV(&rmsV))
{
        // reading of the rmsV succeeded --> perform operations on it
}
else
{
        // reading operation failed... --> retry or in general handle the exception (catch) action
}
```
What do you think about?

**Comment by tiagolobao** [comment]
> I can assure all is properly working here on my testbench. In every case I'll send you new pull request in case some bug to fix will arise (together with the related fixes, naturally!).

Great!

I had an idea. What about something like this:
Removing this line from CS5490::read()
```cpp
  this->_readOperationResult = true;
```
Then adding another method like
```cpp
CS5490::resolve(){
  this->hardwareReset(void);
  this->_readOperationResult = true;
}
```
You do similar in your code. It also gives the possibility to not use the operation result boolean. And you can check whether you want.

**Comment by MaurizioMalaspina** [comment]
Hi Tiago,

ok for the "resolve" method. It could be useful but consider that a reset operation will apply all the default values to the internal registers set --> another setup will be necessary.

It's not so clear to me how you would use the modified code... could you please me send an usage example together with the modified "CS5490::read()" ?

Thank you!

**Comment by tiagolobao** [comment]
> a reset operation will apply all the default values to the internal registers set --> another setup will be necessary.
True. another setup means calling CS5490_SendConfiguration() again?

I think once we don't have CS5490::sendConfiguration() yet, we can use as follows:

Before:
```cpp
double PF = line.getPF();
if (!line.isLastReadingOperationSucceeded()) registerReadingOperationIsOK = false;
uint32_t Igain = line.readReg(16, 33);
if (!line.isLastReadingOperationSucceeded()) registerReadingOperationIsOK = false;
if(registerReadingOperationIsOK)
{
  //Do something
}
else
{
   Serial.println("Critical registes checksum error - CS5490 hardware reset required!");
   resetRequired = true;
}
if(resetRequired)
{
  resetRequired = false;
  measureErrorDetectionCounter = 10;
  communicationMaxRetries = 5;
  line.resolve();
  CS5490_SendConfiguration();
  Serial.println("RESET PERFORMED");
}
```
After adding resolve method
The new methods:
```cpp
void CS5490::read(int page, int address){

	unsigned long startMillis;
	
	this->clearSerialBuffer();

	uint8_t buffer;
	//Select page and address
	if(this->selectedPage != page){
		buffer = (pageByte | (uint8_t)page);
		cSerial->write(buffer);
		this->selectedPage = page;
	}
	buffer = (readByte | (uint8_t)address);
	cSerial->write(buffer);

	startMillis = millis();
	//Wait for 3 bytes to arrive
	while( (cSerial->available() < 3) && ( (millis()-startMillis) < 500));
	if(cSerial->available() >= 3)
	{
		for(int i=0; i<3; i++){
			data[i] = cSerial->read();
		}
                // this->_readOperationResult = true; // (Removing this line)
	}
	else
	{
		this->_readOperationResult = false;
	}

	this->clearSerialBuffer();
}
```

```cpp
CS5490::resolve(){
  this->hardwareReset(void);
  this->_readOperationResult = true;
  // this->sendConfiguration(); //Future method?
}
```

The Example:
```cpp
double PF = line.getPF();
uint32_t Igain = line.readReg(16, 33);
if(line.isLastReadingOperationSucceeded())
{
  //Do something
}
else
{
  resetRequired = true;
}
if(resetRequired)
{
  resetRequired = false;
  measureErrorDetectionCounter = 10;
  communicationMaxRetries = 5;
  line.resolve();
  CS5490_SendConfiguration();
  Serial.println("RESET PERFORMED");
}
```

This avoids multiple "if (!line.isLastReadingOperationSucceeded()) registerReadingOperationIsOK = false;" operations.

**Comment by MaurizioMalaspina** [comment]
Hi Tiago,

crystalline explaination: for me it's OK.

Forget the "CS5490::sendConfiguration()" function or  other callback schemes: simplicity is the best approach and is the aim of Arduino.

I've just committed the modified files (tested on my bench).

I changed "isLastReadingOperationSucceeded" into "areLastReadingOperationsSucceeded" because the method now check a cumulative result of the communication between two line.resolve() calls, in general (take a look to my comments over both the "resolve" and "areLastReadingOperationsSucceeded" methods in teh .cpp).

Let me know if now is ok.

Thank you,
Maurizio

**Comment by tiagolobao** [comment]
> Forget the "CS5490::sendConfiguration()" function or other callback schemes: simplicity is the best approach and is the aim of Arduino.

True. That's also why we're trying to avoid pointers, etc...
Your request is good to go now.

**Comment by MaurizioMalaspina** [comment]
Thank you for merging Tiago!

**Pull request merged**
